using System;
using System.Collections.Generic;
using System.Text;

namespace Tools.Interface.Const
{
    public static class GCP_CSV_COLUMN
    {
        public static string[] MCH_INFO_DT()
        {
            return new string[] { "FIELD_ID", "MCH1_ID", "MCH1_NAME", "MCH2_ID", "MCH2_NAME", "MCH3_ID", "MCH3_NAME", "MCH4_ID", "MCH4_NAME", "MCH5_ID", "MCH5_NAME", "MCH6_ID", "MCH6_NAME" };
        }
        public static string[] STORE_DT()
        {
            return new string[] { "FIELD_ID", "STORE_ID", "STORE_NAME", "STORE_DESCRIPTION", "STORE_OPEN_DATE", "STORE_CLOSED_DATE", "BUSINESS_UNIT", "REGION", "REGION_VN", "CITY_VN", "DISTRICT", "WARD", "ADDRESS", "CUA_HANG_TRUONG", "SDT_CHT", "SDT_CH", "EMAIL_CH", "QLKV", "SDT_QLKV", "EMAIL_QLKV", "GDV", "EMAIL_GDV", "GDM", "EMAIL_GDM", "LATITUDE", "LONGTITUDE", "SIZE_V", "CONCEPT_ID", "CONCEPT", "SUPPLY_REGION", "SIZE_ST", "HUB_HANG_KHO", "STORE_STATUS_DESC", "REF_FC_STORE", "SUPPLY_STORE", "REF_FC_CODE", "CITY", "REGION_DOMAIN", "REGION_DOMAIN_VN", "STORE_STATUS_ID", "IS_WIN_PLUS" };
        }
        public static string[] PRODUCT_DT()
        {
            return new string[] { "FIELD_ID", "PRODUCT_ID", "PRODUCT_NAME", "BASE_UOM", "PRODUCT_TYPE", "MCH1_ID", "MCH2_ID", "MCH3_ID", "MCH4_ID", "MCH5_ID", "MCH6_ID", "MCH1_NAME", "MCH2_NAME", "MCH3_NAME", "MCH4_NAME", "MCH5_NAME", "MCH6_NAME", "TOTAL_SHELF_LIFE", "REMAINING_SHELF_LIFE", "MANUFACTURER_ID", "MANUFACTURER_NAME", "MANUFACTURER", "SUB_MANUFACTURER_ID", "SUB_MANUFACTURER_NAME", "BRAND_ID", "BRAND", "BRAND_NAME", "SUB_BRAND_ID", "SUB_BRAND_NAME", "NAME", "TEMPERATURE", "ORIGIN", "COUNTRY_OF_ORIGIN", "ATTRIBUTE12", "MODEL_DESC", "VAT_CODE", "VAT_DESC" };
        }
        public static string[] PRODUCT_UNIT_DT()
        {
            return new string[] { "FIELD_ID", "PRODUCT_ID", "UNIT", "BARCODE", "BARCODE_FULL", "NUMERATOR", "BASE_UOM" };
        }
        public static string[] SALE_BY_BU_REGION_DT()
        {
            return new string[] { "FIELD_ID", "PRODUCT_ID", "BU", "REGION", "AVG_REVENUE", "AVG_QTY" };
        }

        public static string INSERT_GCP_PRODUCT_UNIT()
        {
            return @"INSERT INTO [dbo].[GCP_PRODUCT_UNIT]
                        ([PRODUCT_ID],[UNIT],[BARCODE],[BARCODE_FULL],[NUMERATOR],[BASE_UOM],[INSERT_DATE],[FIELD_ID])
                            VALUES(@PRODUCT_ID,@UNIT,@BARCODE,@BARCODE_FULL,@NUMERATOR,@BASE_UOM,@INSERT_DATE,@FIELD_ID)";
        }
        public static string INSERT_GCP_PRODUCT()
        {
            return @"INSERT INTO [dbo].[GCP_PRODUCT]
                        ([PRODUCT_ID],[PRODUCT_NAME],[BASE_UOM],[PRODUCT_TYPE],[MCH1_ID],[MCH2_ID],[MCH3_ID],[MCH4_ID],[MCH5_ID],[MCH6_ID],[MCH1_NAME],[MCH2_NAME],[MCH3_NAME],[MCH4_NAME]
                        ,[MCH5_NAME],[MCH6_NAME],[TOTAL_SHELF_LIFE],[REMAINING_SHELF_LIFE],[MANUFACTURER_ID],[MANUFACTURER_NAME],[MANUFACTURER],[SUB_MANUFACTURER_ID],[SUB_MANUFACTURER_NAME]
                        ,[BRAND_ID],[BRAND],[BRAND_NAME],[SUB_BRAND_ID],[SUB_BRAND_NAME],[NAME],[TEMPERATURE],[ORIGIN],[COUNTRY_OF_ORIGIN],[ATTRIBUTE12],[MODEL_DESC],[VAT_CODE],[VAT_DESC],[INSERT_DATE])
                    VALUES(@PRODUCT_ID,@PRODUCT_NAME,@BASE_UOM,@PRODUCT_TYPE,@MCH1_ID,@MCH2_ID,@MCH3_ID,@MCH4_ID,@MCH5_ID,@MCH6_ID,@MCH1_NAME,@MCH2_NAME,@MCH3_NAME,@MCH4_NAME
                        ,@MCH5_NAME,@MCH6_NAME,@TOTAL_SHELF_LIFE,@REMAINING_SHELF_LIFE,@MANUFACTURER_ID,@MANUFACTURER_NAME,@MANUFACTURER,@SUB_MANUFACTURER_ID,@SUB_MANUFACTURER_NAME
                        ,@BRAND_ID,@BRAND,@BRAND_NAME,@SUB_BRAND_ID,@SUB_BRAND_NAME,@NAME,@TEMPERATURE,@ORIGIN,@COUNTRY_OF_ORIGIN,@ATTRIBUTE12,@MODEL_DESC,@VAT_CODE,@VAT_DESC,@INSERT_DATE)";
        }
        public static string INSERT_GCP_STORE()
        {
            return @"INSERT INTO [dbo].[GCP_STORE]
                    ([STORE_ID],[STORE_NAME],[STORE_DESCRIPTION],[STORE_OPEN_DATE],[STORE_CLOSED_DATE],[BUSINESS_UNIT],[REGION],[REGION_VN],[CITY_VN],[DISTRICT]
                    ,[WARD],[ADDRESS],[CUA_HANG_TRUONG],[SDT_CHT],[SDT_CH],[EMAIL_CH],[QLKV],[SDT_QLKV],[EMAIL_QLKV],[GDV],[EMAIL_GDV],[GDM],[EMAIL_GDM],[LATITUDE]
                    ,[LONGTITUDE],[SIZE_V],[CONCEPT_ID],[CONCEPT],[SUPPLY_REGION],[SIZE_ST],[HUB_HANG_KHO],[STORE_STATUS_DESC],[REF_FC_STORE],[SUPPLY_STORE]
                    ,[REF_FC_CODE],[CITY],[REGION_DOMAIN],[REGION_DOMAIN_VN],[STORE_STATUS_ID],[IS_WIN_PLUS],[INSERT_DATE])
                    VALUES (@STORE_ID,@STORE_NAME,@STORE_DESCRIPTION,@STORE_OPEN_DATE,@STORE_CLOSED_DATE,@BUSINESS_UNIT,@REGION,@REGION_VN,@CITY_VN,@DISTRICT
                        ,@WARD,@ADDRESS,@CUA_HANG_TRUONG,@SDT_CHT,@SDT_CH,@EMAIL_CH,@QLKV,@SDT_QLKV,@EMAIL_QLKV,@GDV,@EMAIL_GDV,@GDM,@EMAIL_GDM,@LATITUDE
                        ,@LONGTITUDE,@SIZE_V,@CONCEPT_ID,@CONCEPT,@SUPPLY_REGION,@SIZE_ST,@HUB_HANG_KHO,@STORE_STATUS_DESC,@REF_FC_STORE,@SUPPLY_STORE
                        ,@REF_FC_CODE,@CITY,@REGION_DOMAIN,@REGION_DOMAIN_VN,@STORE_STATUS_ID,@IS_WIN_PLUS,@INSERT_DATE)";
        }
        public static string INSERT_GCP_SALE_BY_BU_REGION()
        {
            return @"INSERT INTO [dbo].[GCP_SALE_BY_BU_REGION] ([FIELD_ID],[PRODUCT_ID],[BU],[REGION],[AVG_REVENUE],[AVG_QTY],[INSERT_DATE])
                                                              VALUES (@FIELD_ID,@PRODUCT_ID,@BU,@REGION,@AVG_REVENUE,@AVG_QTY,@INSERT_DATE)";
        }
    }
}
