using System;
using System.Collections.Generic;
using System.Text;

namespace PhucLong.Interface.Central.Queries
{
    public static class InbQuery
    {
        public static string INB_HEADER_QUERY()
        {
            return @"SELECT [RETAILSTOREID],[BUSINESSDAYDATE],[TRANSACTIONTYPECODE],[WORKSTATIONID],[TRANSACTIONSEQUENCENUMBER],[BEGINDATETIMESTAMP],[ENDDATETIMESTAMP]
                    ,[DEPARTMENT],[OPERATORQUALIFIER],[OPERATORID],[TRANSACTIONCURRENCY],[TRANSACTIONCURRENCY_ISO],[PARTNERQUALIFIER],[PARTNERID],[FIELDGROUP],[FIELDNAME]
                    ,[FIELDVALUE],[UPDATE_FLG],[CRT_DATE],[CHGE_DATE],[ID], LOYALTYSEQUENCENUMBER, CUSTOMERCARDNUMBER
                   FROM [dbo].[INB_SALE_MASTER] (NOLOCK) WHERE [UPDATE_FLG] = 'N' ";
        }

        public static string INB_DETAIL_QUERY()
        {
            return @"SELECT [RETAILSTOREID],[TRANSACTIONSEQUENCENUMBER],[TRANSACTIONTYPECODE],[BUSINESSDAYDATE], [WORKSTATIONID], [RETAILSEQUENCENUMBER],[RETAILTYPECODE],[RETAILREASONCODE],[ITEMIDQUALIFIER]
	                       ,[ITEMID],[RETAILQUANTITY],[SALESUNITOFMEASURE],[SALESUNITOFMEASURE_ISO],[SALESAMOUNT],[NORMALSALESAMOUNT],[COST]
	                       ,[BATCHID],[SERIALNUMBER],[PROMOTIONID],[ACTUALUNITPRICE],[ORDER_CHANNEL],[TAXSEQUENCENUMBER],[TAXTYPECODE],[TAXAMOUNT], FIELDGROUP, FIELDNAME, FIELDVALUE, [UPDATE_FLG]
                    FROM [dbo].[INB_SALE_DETAIL] (NOLOCK)
                    WHERE [TRANSACTIONSEQUENCENUMBER] IN @TRANSACTIONSEQUENCENUMBER;";
        }

        public static string INB_TENDER_QUERY()
        {
            return @"SELECT [RETAILSTOREID],[TRANSACTIONSEQUENCENUMBER],[TRANSACTIONTYPECODE],[BUSINESSDAYDATE], [WORKSTATIONID], [TENDERSEQUENCENUMBER],[TENDERTYPECODE],[TENDERAMOUNT],[TENDERCURRENCY],[TENDERCURRENCY_ISO],[REFERENCEID]
                    ,[PAYMENTCARD],[CARDNUMBER],[CARDNUMBERSUFFIX],[CARDEXPIRATIONDATE],[CARDHOLDERNAME],[ADJUDICATIONCODE],[AUTHORIZATIONDATETIME],[AUTHORIZATIONCODE]
                    ,[REQUESTEDAMOUNT],[CARDTYPE],[LOYALTYSEQUENCENUMBER],[CUSTOMERCARDNUMBER],[UPDATE_FLG], AUTHORIZINGTERMID
                    FROM [dbo].[INB_SALE_TENDER] (NOLOCK) 
                    WHERE [TRANSACTIONSEQUENCENUMBER] IN @TRANSACTIONSEQUENCENUMBER;";
        }

        public static string INB_DISCOUNT_QUERY()
        {
            return @"SELECT [RETAILSTOREID],[TRANSACTIONSEQUENCENUMBER],[TRANSACTIONTYPECODE],[BUSINESSDAYDATE], [WORKSTATIONID], [RETAILSEQUENCENUMBER],[DISCOUNTSEQUENCENUMBER],[DISCOUNTTYPECODE],[DISCOUNTREASONCODE]
                    ,[REDUCTIONAMOUNT],[DISCOUNTID],[BONUSBUYID],[OFFERID]
                    FROM [dbo].[INB_SALE_DISCOUNT] (NOLOCK) 
                    WHERE [TRANSACTIONSEQUENCENUMBER] IN @TRANSACTIONSEQUENCENUMBER;";
        }

        public static string INB_B02_RECONCILE_QUERY()
        {
            return @"SELECT * FROM INB_B02_RECONCILE (NOLOCK) WHERE [UpdateFlg] = 'N'";
        }
    }
}
